version: '3.8'

services:

  api_service:
      container_name: sitas-api
      build: .
      restart: unless-stopped
      ports:
        - 8089:8089
      environment:
        SPRING_DATASOURCE_URL: ${DB_URL}
        SPRING_DATASOURCE_USERNAME: ${DB_USER}
        SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_JPA_SHOW_SQL: true
        
env_file:
  - .env

  