spring.application.name=sitas
server.port=8011
#Set path for the app
server.servlet.context-path=/modulo-05-auth

#Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#SPRING DOC (SWAGGER) CONFIGURATION
springdoc.swagger-ui.path=/doc/swagger-ui.html
# /api-docs endpoint custom path
springdoc.api-docs.path=/api-docs

#enable / disable swagger-ui
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#Actuator configuration
management.metrics.tags.application=${spring.application.name}
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#Authorization
airline-api.jwt.rsa-pub-key=classpath:public_key.der

#codefact.p12 configuration
# server.ssl.key-store=classpath:codefact.p12
# server.ssl.key-store-password=123456
# server.ssl.enabled-protocols=TLSv1.2
# server.ssl.key-store-type=PKCS12